language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"

before_script:
  - yarn global add gulp-cli

addons:
  sonarcloud:
    organization: "avegao-github"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
  - gulp

cache:
  yarn: true
